site_name: 'sorbay documentation'
docs_dir: './docs/en'                        # Where to find the English markdown files
site_dir: './generated'                      # Where to put the English HTML files
site_url: 'https://doc.sorbay.com'

theme:
  name: material
  custom_dir: './overrides/'                  # This is where the customization of the theme lives
  logo: assets/images/sorbay-blue-white.png                 # The logo is shared by all languages
  favicon: assets/images/favicon.png              # The favicon is shared by all languages
  language: en                                    # The build's language
extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search:
      lang: en                                      # Set language for search

nav:
  - Welcome: 'index.md'
  - Profile: 'profile.md'
  - Workspaces: 'workspaces.md'
  - Services:
    - About: 'services.md'
    - sorbay_ciam: 'sorbay_ciam.md'
  - Members: 'members.md'
  - Settings: 'settings.md'
  - Help: 'help.md'
