site_name: 'Sorbay documentation'
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../generated/en'                      # Where to put the English HTML files

theme:
  name: material
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  logo: assets/images/favicon.png                    # The logo is shared by all languages
  favicon: assets/images/favicon.png              # The favicon is shared by all languages
  language: en
  features:
    - navigation.indexes # The build's language
extra_css:
  - assets/stylesheets/extra.css

extra:                                              # Language Selection
  alternate:

    # Switch to English
    - name: English
      link: /en/
      lang: en
    # Switch to French
    - name: Deutsch
      link: /de/
      lang: de

plugins:
  - search:
      lang: en                                      # Set language for search

nav:
  - Welcome: index.md
